CREATE TABLE DEPT(
	DEPTNO INT,
	DNAME VARCHAR(30) NOT NULL UNIQUE, -- Column constraint
	LOC VARCHAR(30) NOT NULL, -- NOT NULL always at column level
	
	CONSTRAINT PK_DEPT PRIMARY KEY(DEPTNO), --Using CONSTRAINT we are giving a name to constraint as PK_DEPT
	
	CONSTRAINT DEPTNO_VALUES CHECK (DEPTNO = 10 OR --Table Level constraint
									DEPTNO = 20 OR
									DEPTNO = 30 OR
									DEPTNO = 40 OR
									DEPTNO = 50 ));
									
									
-- Insert a record into Table
-- INSERT INTO <table_name> [(column, column,...)] VALUES(value1,value2,...);
INSERT INTO DEPT(deptno,dname,loc) VALUES(10,'FINANCE','MUMBAI');
INSERT INTO DEPT(loc,dname,deptno) VALUES('HYDERABAD','LOGISTICS',20);
SELECT * FROM DEPT;

-- Data is provided for all fields
INSERT INTO DEPT VALUES(30,'SALES','BENGALURU');--Sequence of values should match with sequence of 
INSERT INTO DEPT VALUES(40,'PRODUCTION','CHENNAI');

/*WHERE*/
-- VALUES ARE RETURNED IN THE FORM OF RESULT SET FROM RDBMS
SELECT * FROM DEPT WHERE DEPTNO = 10;
SELECT * FROM DEPT WHERE DEPTNO > 10;
SELECT * FROM DEPT WHERE LOC = 'HYDERABAD';
SELECT * FROM DEPT WHERE DEPTNO IN (10,20,30);
SELECT * FROM DEPT WHERE DEPTNO NOT IN (10,20,30);
SELECT * FROM DEPT WHERE LOC != 'HYDERABAD';
SELECT * FROM DEPT WHERE LOC <> 'MUMBAI';
SELECT * FROM DEPT WHERE DEPTNO BETWEEN 10 AND 30;
SELECT * FROM DEPT WHERE DEPTNO NOT BETWEEN 10 AND 30;
SELECT DEPTNO,LOC FROM DEPT;
SELECT * FROM DEPT ORDER BY LOC ASC;
SELECT * FROM DEPT ORDER BY LOC DESC;

SELECT VERSION();

SELECT DEPTNO AS DEPARTMENT_NUMBER,
		DNAME AS DEPARTMENT_NAME,
		LOC AS LOCATIONS FROM DEPT;
