spring:
  application:
    name: product-service
    
  datasource:
    username: root
    password: Jayak@013
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product    
  jpa:
    hibernate:
      ddl-auto: update
      
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka
