spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
#The below property will provide the default end points of gateway api using eureka client
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true 
       
resilience4j.circuitbreaker:
  configs:
#    accountsCircuitBreaker:
     default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true 
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "ZettaBank Gateway Server Application"
    version: "1.0.0"