create table customer(
    cust_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY, 
	first_name varchar(20) not null, 
	last_name varchar(20) not null, 
	gender varchar(6) check(gender IN ('male','female','others')) not null, 
	mobile varchar(10) not null, 
	aadhaar_no varchar(20) unique not null,
	pic_name varchar(20) not null,
	address varchar(30) not null
);

create table customer_credentials(
                                 username varchar(20) PRIMARY KEY, 
                                 password varchar(20) not null, 
                                 user_type varchar(10) check(user_type IN ('customer','admin')),
								 cust_id int,
                                 foreign key(cust_id) references customer(cust_id)
);

create table account( account_no INT GENERATED BY DEFAULT AS IDENTITY (START WITH 50000) PRIMARY KEY, 
	             balance decimal(10,2) check(balance>=0),
	             created_on date,
	             cust_id int,
				 foreign key(cust_id) references customer(cust_id)
);

create table transaction(
			transaction_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
			transfer_from int,
			transfer_to int,
			amount decimal(10,2) check(amount>0) not null,
			transaction_type varchar(10) check(transaction_type IN ('debit','credit','transfer')),
			date_of_transaction date,
			closing_balance decimal(10,2) check(closing_balance>=0),
			account_no int,
			foreign key(account_no) references account(account_no)
			);